/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { MedicalHistory } from "./MedicalHistory";
import { MedicalHistoryCountArgs } from "./MedicalHistoryCountArgs";
import { MedicalHistoryFindManyArgs } from "./MedicalHistoryFindManyArgs";
import { MedicalHistoryFindUniqueArgs } from "./MedicalHistoryFindUniqueArgs";
import { CreateMedicalHistoryArgs } from "./CreateMedicalHistoryArgs";
import { UpdateMedicalHistoryArgs } from "./UpdateMedicalHistoryArgs";
import { DeleteMedicalHistoryArgs } from "./DeleteMedicalHistoryArgs";
import { Doctor } from "../../doctor/base/Doctor";
import { User } from "../../user/base/User";
import { MedicalHistoryDto } from "../MedicalHistoryDto";
import { MedicalHistoryService } from "../medicalHistory.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MedicalHistory)
export class MedicalHistoryResolverBase {
  constructor(
    protected readonly service: MedicalHistoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MedicalHistory",
    action: "read",
    possession: "any",
  })
  async _medicalHistoriesMeta(
    @graphql.Args() args: MedicalHistoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MedicalHistory])
  @nestAccessControl.UseRoles({
    resource: "MedicalHistory",
    action: "read",
    possession: "any",
  })
  async medicalHistories(
    @graphql.Args() args: MedicalHistoryFindManyArgs
  ): Promise<MedicalHistory[]> {
    return this.service.medicalHistories(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MedicalHistory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MedicalHistory",
    action: "read",
    possession: "own",
  })
  async medicalHistory(
    @graphql.Args() args: MedicalHistoryFindUniqueArgs
  ): Promise<MedicalHistory | null> {
    const result = await this.service.medicalHistory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MedicalHistory)
  @nestAccessControl.UseRoles({
    resource: "MedicalHistory",
    action: "create",
    possession: "any",
  })
  async createMedicalHistory(
    @graphql.Args() args: CreateMedicalHistoryArgs
  ): Promise<MedicalHistory> {
    return await this.service.createMedicalHistory({
      ...args,
      data: {
        ...args.data,

        doctor: args.data.doctor
          ? {
              connect: args.data.doctor,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MedicalHistory)
  @nestAccessControl.UseRoles({
    resource: "MedicalHistory",
    action: "update",
    possession: "any",
  })
  async updateMedicalHistory(
    @graphql.Args() args: UpdateMedicalHistoryArgs
  ): Promise<MedicalHistory | null> {
    try {
      return await this.service.updateMedicalHistory({
        ...args,
        data: {
          ...args.data,

          doctor: args.data.doctor
            ? {
                connect: args.data.doctor,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MedicalHistory)
  @nestAccessControl.UseRoles({
    resource: "MedicalHistory",
    action: "delete",
    possession: "any",
  })
  async deleteMedicalHistory(
    @graphql.Args() args: DeleteMedicalHistoryArgs
  ): Promise<MedicalHistory | null> {
    try {
      return await this.service.deleteMedicalHistory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Doctor, {
    nullable: true,
    name: "doctor",
  })
  @nestAccessControl.UseRoles({
    resource: "Doctor",
    action: "read",
    possession: "any",
  })
  async getDoctor(
    @graphql.Parent() parent: MedicalHistory
  ): Promise<Doctor | null> {
    const result = await this.service.getDoctor(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: MedicalHistory
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Query(() => MedicalHistoryDto)
  async GetMedicalHistoryById(
    @graphql.Args("args")
    args: string
  ): Promise<MedicalHistoryDto> {
    return this.service.GetMedicalHistoryById(args);
  }

  @graphql.Query(() => [MedicalHistoryDto])
  async ListMedicalHistories(
    @graphql.Args()
    args: MedicalHistoryDto[]
  ): Promise<MedicalHistoryDto[]> {
    return this.service.ListMedicalHistories(args);
  }
}
