/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { MedicalHistoryUpdateManyWithoutDoctorsInput } from "./MedicalHistoryUpdateManyWithoutDoctorsInput";
import { Type } from "class-transformer";
import { MedicalTestUpdateManyWithoutDoctorsInput } from "./MedicalTestUpdateManyWithoutDoctorsInput";
import { TransactionUpdateManyWithoutDoctorsInput } from "./TransactionUpdateManyWithoutDoctorsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class DoctorUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => MedicalHistoryUpdateManyWithoutDoctorsInput,
  })
  @ValidateNested()
  @Type(() => MedicalHistoryUpdateManyWithoutDoctorsInput)
  @IsOptional()
  @Field(() => MedicalHistoryUpdateManyWithoutDoctorsInput, {
    nullable: true,
  })
  medicalHistories?: MedicalHistoryUpdateManyWithoutDoctorsInput;

  @ApiProperty({
    required: false,
    type: () => MedicalTestUpdateManyWithoutDoctorsInput,
  })
  @ValidateNested()
  @Type(() => MedicalTestUpdateManyWithoutDoctorsInput)
  @IsOptional()
  @Field(() => MedicalTestUpdateManyWithoutDoctorsInput, {
    nullable: true,
  })
  medicalTests?: MedicalTestUpdateManyWithoutDoctorsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  specialty?: string | null;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutDoctorsInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutDoctorsInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutDoctorsInput, {
    nullable: true,
  })
  transactions?: TransactionUpdateManyWithoutDoctorsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { DoctorUpdateInput as DoctorUpdateInput };
